##### BASE STYLE (Gruvbox Material Hard) #####
set -g status-style fg=#654735,bg=#f5edca
set -g message-style fg=#4f3829,bg=#f3eac7
set -g pane-border-style fg=#a89984
set -g pane-active-border-style fg=#45707a

##### WINDOW LIST #####
set -g window-status-style fg=#7c6f64,bg=#f5edca
set -g window-status-format " #I:#W "

set -g window-status-current-style fg=#654735,bg=#f3eac7
set -g window-status-current-format " #[fg=#45707a]#I#[fg=#654735]:#W "

##### LEFT SIDE #####
set -g status-left "#[fg=#45707a]#S #[fg=#a89984]•"

##### RIGHT SIDE #####
set -g status-right "\
#[fg=#4c7a5d]#(whoami) \
#[fg=#a89984]• \
#[fg=#c35e0a]%H:%M \
#[fg=#a89984]• \
#[fg=#7c6f64]%d %b"
