##### BASE STYLE (Kanagawa Dragon) #####
set -g status-style fg=#c5c9c5,bg=#181616
set -g message-style fg=#c5c9c5,bg=#282727
set -g pane-border-style fg=#625e5a
set -g pane-active-border-style fg=#8ba4b0

##### WINDOW LIST #####
set -g window-status-style fg=#a6a69c,bg=#181616
set -g window-status-format " #I:#W "

set -g window-status-current-style fg=#c5c9c5,bg=#282727
set -g window-status-current-format " #[fg=#8ba4b0]#I#[fg=#c5c9c5]:#W "

##### LEFT SIDE #####
set -g status-left "#[fg=#8ba4b0]#S #[fg=#625e5a]•"

##### RIGHT SIDE #####
set -g status-right "\
#[fg=#87a987]#(whoami) \
#[fg=#625e5a]• \
#[fg=#b6927b]%H:%M \
#[fg=#625e5a]• \
#[fg=#a6a69c]%d %b"
