##### BASE STYLE (Solarized Light) #####
set -g status-style fg=#657b83,bg=#fdf6e3
set -g message-style fg=#657b83,bg=#eee8d5
set -g pane-border-style fg=#93a1a1
set -g pane-active-border-style fg=#268bd2

##### WINDOW LIST #####
set -g window-status-style fg=#93a1a1,bg=#fdf6e3
set -g window-status-format " #I:#W "

set -g window-status-current-style fg=#657b83,bg=#eee8d5
set -g window-status-current-format " #[fg=#268bd2]#I#[fg=#657b83]:#W "

##### LEFT SIDE #####
set -g status-left "#[fg=#268bd2]#S #[fg=#93a1a1]•"

##### RIGHT SIDE #####
set -g status-right "\
#[fg=#859900]#(whoami) \
#[fg=#93a1a1]• \
#[fg=#b58900]%H:%M \
#[fg=#93a1a1]• \
#[fg=#93a1a1]%d %b"
