##### BASE STYLE (Gruvbox Material Hard) #####
set -g status-style fg=#ddc7a1,bg=#282828
set -g message-style fg=#ddc7a1,bg=#32302f
set -g pane-border-style fg=#7c6f64
set -g pane-active-border-style fg=#7daea3

##### WINDOW LIST #####
set -g window-status-style fg=#a89984,bg=#282828
set -g window-status-format " #I:#W "

set -g window-status-current-style fg=#ddc7a1,bg=#32302f
set -g window-status-current-format " #[fg=#7daea3]#I#[fg=#ddc7a1]:#W "

##### LEFT SIDE #####
set -g status-left "#[fg=#7daea3]#S #[fg=#7c6f64]•"

##### RIGHT SIDE #####
set -g status-right "\
#[fg=#89b482]#(whoami) \
#[fg=#7c6f64]• \
#[fg=#e78a4e]%H:%M \
#[fg=#7c6f64]• \
#[fg=#a89984]%d %b"
