##### BASE STYLE (Kanagawa Lotus) #####
set -g status-style fg=#545464,bg=#f2ecbc
set -g message-style fg=#43436c,bg=#e5ddb0
set -g pane-border-style fg=#a09cac
set -g pane-active-border-style fg=#4d699b

##### WINDOW LIST #####
set -g window-status-style fg=#8a8980,bg=#f2ecbc
set -g window-status-format " #I:#W "

set -g window-status-current-style fg=#545464,bg=#e7dba0
set -g window-status-current-format " #[fg=#4d699b]#I#[fg=#545464]:#W "

##### LEFT SIDE #####
set -g status-left "#[fg=#4d699b]#S #[fg=#a09cac]•"

##### RIGHT SIDE #####
set -g status-right "\
#[fg=#6f894e]#(whoami) \
#[fg=#a09cac]• \
#[fg=#cc6d00]%H:%M \
#[fg=#a09cac]• \
#[fg=#8a8980]%d %b"
